CHANGELOG_FILENAME='CHANGELOG.md'
CHANGELOG_HEADER="# What's new?
"
CHANGELOG_INCLUDE_TIMESTAMP=true

#INTERNAL
CHANGELOG_MKTEMP_OPTIONS="--tmpdir changelog-sh-tmp.XXXXXXXX"
CHANGELOG_DIFF_OPTIONS="--color=always -u"